/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type User2BusinessOverridesProps = {
    "0"?: PrimitiveOverrideProps<TextProps>;
    "25"?: PrimitiveOverrideProps<TextProps>;
    "39"?: PrimitiveOverrideProps<TextProps>;
    "43"?: PrimitiveOverrideProps<TextProps>;
    "50"?: PrimitiveOverrideProps<TextProps>;
    "67"?: PrimitiveOverrideProps<TextProps>;
    "75"?: PrimitiveOverrideProps<TextProps>;
    "100"?: PrimitiveOverrideProps<TextProps>;
    User2Business?: PrimitiveOverrideProps<ViewProps>;
    "Business Dashboard "?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 46225"?: PrimitiveOverrideProps<ViewProps>;
    "Header Logo529"?: PrimitiveOverrideProps<ImageProps>;
    "Header background 530"?: PrimitiveOverrideProps<ViewProps>;
    "Profile [default pic]531"?: PrimitiveOverrideProps<IconProps>;
    Dashboard532?: PrimitiveOverrideProps<TextProps>;
    Analytics534?: PrimitiveOverrideProps<TextProps>;
    "Product Catalog533"?: PrimitiveOverrideProps<TextProps>;
    "[ biz name] Dashboard224"?: PrimitiveOverrideProps<TextProps>;
    "Featured Products"?: PrimitiveOverrideProps<TextProps>;
    "Full Catalog"?: PrimitiveOverrideProps<TextProps>;
    Item438?: PrimitiveOverrideProps<ViewProps>;
    "Product background439"?: PrimitiveOverrideProps<IconProps>;
    "Item Photo4310"?: PrimitiveOverrideProps<IconProps>;
    "Product Name4311"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range4312"?: PrimitiveOverrideProps<TextProps>;
    Ratings4313?: PrimitiveOverrideProps<ViewProps>;
    Star4314?: PrimitiveOverrideProps<IconProps>;
    Star4315?: PrimitiveOverrideProps<IconProps>;
    Star4316?: PrimitiveOverrideProps<IconProps>;
    Star4317?: PrimitiveOverrideProps<IconProps>;
    Star4318?: PrimitiveOverrideProps<IconProps>;
    Item4319?: PrimitiveOverrideProps<ViewProps>;
    "Product background4320"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo4321"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name4322"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range4323"?: PrimitiveOverrideProps<TextProps>;
    Ratings4324?: PrimitiveOverrideProps<ViewProps>;
    Star4325?: PrimitiveOverrideProps<IconProps>;
    Star4326?: PrimitiveOverrideProps<IconProps>;
    Star4327?: PrimitiveOverrideProps<IconProps>;
    Star4328?: PrimitiveOverrideProps<IconProps>;
    Star4329?: PrimitiveOverrideProps<IconProps>;
    Item4330?: PrimitiveOverrideProps<ViewProps>;
    "Product background4331"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo4332"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name4333"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range4334"?: PrimitiveOverrideProps<TextProps>;
    Ratings4335?: PrimitiveOverrideProps<ViewProps>;
    Star4336?: PrimitiveOverrideProps<IconProps>;
    Star4337?: PrimitiveOverrideProps<IconProps>;
    Star4338?: PrimitiveOverrideProps<IconProps>;
    Star4339?: PrimitiveOverrideProps<IconProps>;
    Star4340?: PrimitiveOverrideProps<IconProps>;
    Item4341?: PrimitiveOverrideProps<ViewProps>;
    "Product background4342"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo4343"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name4344"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range4345"?: PrimitiveOverrideProps<TextProps>;
    Ratings4346?: PrimitiveOverrideProps<ViewProps>;
    Star4347?: PrimitiveOverrideProps<IconProps>;
    Star4348?: PrimitiveOverrideProps<IconProps>;
    Star4349?: PrimitiveOverrideProps<IconProps>;
    Star4350?: PrimitiveOverrideProps<IconProps>;
    Star4351?: PrimitiveOverrideProps<IconProps>;
    Item43140?: PrimitiveOverrideProps<ViewProps>;
    "Product background43141"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo43142"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name43143"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range43144"?: PrimitiveOverrideProps<TextProps>;
    Ratings43145?: PrimitiveOverrideProps<ViewProps>;
    Star43146?: PrimitiveOverrideProps<IconProps>;
    Star43147?: PrimitiveOverrideProps<IconProps>;
    Star43148?: PrimitiveOverrideProps<IconProps>;
    Star43149?: PrimitiveOverrideProps<IconProps>;
    Star43150?: PrimitiveOverrideProps<IconProps>;
    Item43151?: PrimitiveOverrideProps<ViewProps>;
    "Product background43152"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo43153"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name43154"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range43155"?: PrimitiveOverrideProps<TextProps>;
    Ratings43156?: PrimitiveOverrideProps<ViewProps>;
    Star43157?: PrimitiveOverrideProps<IconProps>;
    Star43158?: PrimitiveOverrideProps<IconProps>;
    Star43159?: PrimitiveOverrideProps<IconProps>;
    Star43160?: PrimitiveOverrideProps<IconProps>;
    Star43161?: PrimitiveOverrideProps<IconProps>;
    Item43162?: PrimitiveOverrideProps<ViewProps>;
    "Product background43163"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo43164"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name43165"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range43166"?: PrimitiveOverrideProps<TextProps>;
    Ratings43167?: PrimitiveOverrideProps<ViewProps>;
    Star43168?: PrimitiveOverrideProps<IconProps>;
    Star43169?: PrimitiveOverrideProps<IconProps>;
    Star43170?: PrimitiveOverrideProps<IconProps>;
    Star43171?: PrimitiveOverrideProps<IconProps>;
    Star43172?: PrimitiveOverrideProps<IconProps>;
    Item43173?: PrimitiveOverrideProps<ViewProps>;
    "Product background43174"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo43175"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name43176"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range43177"?: PrimitiveOverrideProps<TextProps>;
    Ratings43178?: PrimitiveOverrideProps<ViewProps>;
    Star43179?: PrimitiveOverrideProps<IconProps>;
    Star43180?: PrimitiveOverrideProps<IconProps>;
    Star43181?: PrimitiveOverrideProps<IconProps>;
    Star43182?: PrimitiveOverrideProps<IconProps>;
    Star43183?: PrimitiveOverrideProps<IconProps>;
    Item4396?: PrimitiveOverrideProps<ViewProps>;
    "Product background4397"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo4398"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name4399"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range43100"?: PrimitiveOverrideProps<TextProps>;
    Ratings43101?: PrimitiveOverrideProps<ViewProps>;
    Star43102?: PrimitiveOverrideProps<IconProps>;
    Star43103?: PrimitiveOverrideProps<IconProps>;
    Star43104?: PrimitiveOverrideProps<IconProps>;
    Star43105?: PrimitiveOverrideProps<IconProps>;
    Star43106?: PrimitiveOverrideProps<IconProps>;
    Item43107?: PrimitiveOverrideProps<ViewProps>;
    "Product background43108"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo43109"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name43110"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range43111"?: PrimitiveOverrideProps<TextProps>;
    Ratings43112?: PrimitiveOverrideProps<ViewProps>;
    Star43113?: PrimitiveOverrideProps<IconProps>;
    Star43114?: PrimitiveOverrideProps<IconProps>;
    Star43115?: PrimitiveOverrideProps<IconProps>;
    Star43116?: PrimitiveOverrideProps<IconProps>;
    Star43117?: PrimitiveOverrideProps<IconProps>;
    Item43118?: PrimitiveOverrideProps<ViewProps>;
    "Product background43119"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo43120"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name43121"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range43122"?: PrimitiveOverrideProps<TextProps>;
    Ratings43123?: PrimitiveOverrideProps<ViewProps>;
    Star43124?: PrimitiveOverrideProps<IconProps>;
    Star43125?: PrimitiveOverrideProps<IconProps>;
    Star43126?: PrimitiveOverrideProps<IconProps>;
    Star43127?: PrimitiveOverrideProps<IconProps>;
    Star43128?: PrimitiveOverrideProps<IconProps>;
    Item43129?: PrimitiveOverrideProps<ViewProps>;
    "Product background43130"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo43131"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name43132"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range43133"?: PrimitiveOverrideProps<TextProps>;
    Ratings43134?: PrimitiveOverrideProps<ViewProps>;
    Star43135?: PrimitiveOverrideProps<IconProps>;
    Star43136?: PrimitiveOverrideProps<IconProps>;
    Star43137?: PrimitiveOverrideProps<IconProps>;
    Star43138?: PrimitiveOverrideProps<IconProps>;
    Star43139?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 6"?: PrimitiveOverrideProps<IconProps>;
    edit435?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 7"?: PrimitiveOverrideProps<IconProps>;
    edit437?: PrimitiveOverrideProps<TextProps>;
    "Product/Service View [Customer Preview w/o edit button] "?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4643817"?: PrimitiveOverrideProps<ViewProps>;
    "Header Logo43818"?: PrimitiveOverrideProps<ImageProps>;
    "Header background 43819"?: PrimitiveOverrideProps<ViewProps>;
    "Profile [default pic]43820"?: PrimitiveOverrideProps<IconProps>;
    Dashboard43821?: PrimitiveOverrideProps<TextProps>;
    Analytics43822?: PrimitiveOverrideProps<TextProps>;
    "Product Catalog43823"?: PrimitiveOverrideProps<TextProps>;
    "[ biz name] Dashboard43824"?: PrimitiveOverrideProps<TextProps>;
    Item43827?: PrimitiveOverrideProps<ViewProps>;
    "Product background43828"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo43829"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name43830"?: PrimitiveOverrideProps<TextProps>;
    $$$43831?: PrimitiveOverrideProps<TextProps>;
    Ratings43832?: PrimitiveOverrideProps<ViewProps>;
    Star43833?: PrimitiveOverrideProps<IconProps>;
    Star43834?: PrimitiveOverrideProps<IconProps>;
    Star43835?: PrimitiveOverrideProps<IconProps>;
    Star43836?: PrimitiveOverrideProps<IconProps>;
    Star43837?: PrimitiveOverrideProps<IconProps>;
    "Button Child Frame431198"?: PrimitiveOverrideProps<ViewProps>;
    "Button 1431199"?: PrimitiveOverrideProps<ViewProps>;
    "Text 1431200"?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 8431207"?: PrimitiveOverrideProps<IconProps>;
    edit431208?: PrimitiveOverrideProps<TextProps>;
    "Review/Ratings View "?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 46431240"?: PrimitiveOverrideProps<ViewProps>;
    "Header Logo431241"?: PrimitiveOverrideProps<ImageProps>;
    "Header background 431242"?: PrimitiveOverrideProps<ViewProps>;
    "Profile [default pic]431243"?: PrimitiveOverrideProps<IconProps>;
    Dashboard431244?: PrimitiveOverrideProps<TextProps>;
    Analytics431245?: PrimitiveOverrideProps<TextProps>;
    "Product Catalog431246"?: PrimitiveOverrideProps<TextProps>;
    "[ biz name] Dashboard431247"?: PrimitiveOverrideProps<TextProps>;
    "Business Profile 7"?: PrimitiveOverrideProps<ViewProps>;
    "bid-profile16345"?: PrimitiveOverrideProps<ViewProps>;
    "<----------------------- Review Goes Here ----------------------->6346"?: PrimitiveOverrideProps<TextProps>;
    "Review Title6347"?: PrimitiveOverrideProps<TextProps>;
    "@username6348"?: PrimitiveOverrideProps<TextProps>;
    "User Name6349"?: PrimitiveOverrideProps<TextProps>;
    "user-icon6350"?: PrimitiveOverrideProps<IconProps>;
    "Business Profile 6"?: PrimitiveOverrideProps<ViewProps>;
    "bid-profile16352"?: PrimitiveOverrideProps<ViewProps>;
    "<----------------------- Review Goes Here ----------------------->6353"?: PrimitiveOverrideProps<TextProps>;
    "Review Title6354"?: PrimitiveOverrideProps<TextProps>;
    "@username6355"?: PrimitiveOverrideProps<TextProps>;
    "User Name6356"?: PrimitiveOverrideProps<TextProps>;
    "user-icon6357"?: PrimitiveOverrideProps<IconProps>;
    "Business Profile 5"?: PrimitiveOverrideProps<ViewProps>;
    "bid-profile16338"?: PrimitiveOverrideProps<ViewProps>;
    "<----------------------- Review Goes Here ----------------------->6339"?: PrimitiveOverrideProps<TextProps>;
    "Review Title6340"?: PrimitiveOverrideProps<TextProps>;
    "@username6341"?: PrimitiveOverrideProps<TextProps>;
    "User Name6342"?: PrimitiveOverrideProps<TextProps>;
    "user-icon6343"?: PrimitiveOverrideProps<IconProps>;
    Item431248?: PrimitiveOverrideProps<ViewProps>;
    "Product background431249"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo431250"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name431251"?: PrimitiveOverrideProps<TextProps>;
    $$$431252?: PrimitiveOverrideProps<TextProps>;
    Ratings431253?: PrimitiveOverrideProps<ViewProps>;
    Star431254?: PrimitiveOverrideProps<IconProps>;
    Star431255?: PrimitiveOverrideProps<IconProps>;
    Star431256?: PrimitiveOverrideProps<IconProps>;
    Star431257?: PrimitiveOverrideProps<IconProps>;
    Star431258?: PrimitiveOverrideProps<IconProps>;
    "Reply Button6358"?: PrimitiveOverrideProps<ViewProps>;
    "Button 16359"?: PrimitiveOverrideProps<ViewProps>;
    "Text 16360"?: PrimitiveOverrideProps<TextProps>;
    "Reply Button6361"?: PrimitiveOverrideProps<ViewProps>;
    "Button 16362"?: PrimitiveOverrideProps<ViewProps>;
    "Text 16363"?: PrimitiveOverrideProps<TextProps>;
    "Reply button"?: PrimitiveOverrideProps<ViewProps>;
    "Button 16365"?: PrimitiveOverrideProps<ViewProps>;
    "Text 16366"?: PrimitiveOverrideProps<TextProps>;
    Ratings6319?: PrimitiveOverrideProps<ViewProps>;
    Star6320?: PrimitiveOverrideProps<IconProps>;
    Star6321?: PrimitiveOverrideProps<IconProps>;
    Star6322?: PrimitiveOverrideProps<IconProps>;
    Star6323?: PrimitiveOverrideProps<IconProps>;
    Star6324?: PrimitiveOverrideProps<IconProps>;
    Ratings6325?: PrimitiveOverrideProps<ViewProps>;
    Star6326?: PrimitiveOverrideProps<IconProps>;
    Star6327?: PrimitiveOverrideProps<IconProps>;
    Star6328?: PrimitiveOverrideProps<IconProps>;
    Star6329?: PrimitiveOverrideProps<IconProps>;
    Star6330?: PrimitiveOverrideProps<IconProps>;
    Ratings6331?: PrimitiveOverrideProps<ViewProps>;
    Star6332?: PrimitiveOverrideProps<IconProps>;
    Star6333?: PrimitiveOverrideProps<IconProps>;
    Star6334?: PrimitiveOverrideProps<IconProps>;
    Star6335?: PrimitiveOverrideProps<IconProps>;
    Star6336?: PrimitiveOverrideProps<IconProps>;
    "Product/Service View [Edit/Update] "?: PrimitiveOverrideProps<ViewProps>;
    Item632?: PrimitiveOverrideProps<ViewProps>;
    "Product background633"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo634"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name635"?: PrimitiveOverrideProps<TextProps>;
    $$$636?: PrimitiveOverrideProps<TextProps>;
    Ratings637?: PrimitiveOverrideProps<ViewProps>;
    Star638?: PrimitiveOverrideProps<IconProps>;
    Star639?: PrimitiveOverrideProps<IconProps>;
    Star6310?: PrimitiveOverrideProps<IconProps>;
    Star6311?: PrimitiveOverrideProps<IconProps>;
    Star6312?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 46431210"?: PrimitiveOverrideProps<ViewProps>;
    "Header Logo431211"?: PrimitiveOverrideProps<ImageProps>;
    "Header background 431212"?: PrimitiveOverrideProps<ViewProps>;
    "Profile [default pic]431213"?: PrimitiveOverrideProps<IconProps>;
    Dashboard431214?: PrimitiveOverrideProps<TextProps>;
    Analytics431215?: PrimitiveOverrideProps<TextProps>;
    "Product Catalog431216"?: PrimitiveOverrideProps<TextProps>;
    "[ biz name] Dashboard431217"?: PrimitiveOverrideProps<TextProps>;
    "Button Child Frame431229"?: PrimitiveOverrideProps<ViewProps>;
    "Button 1431230"?: PrimitiveOverrideProps<ViewProps>;
    "Text 1431231"?: PrimitiveOverrideProps<TextProps>;
    "Button Child Frame431232"?: PrimitiveOverrideProps<ViewProps>;
    "Button 1431233"?: PrimitiveOverrideProps<ViewProps>;
    "Text 1431234"?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 8431235"?: PrimitiveOverrideProps<IconProps>;
    edit431236?: PrimitiveOverrideProps<TextProps>;
    "[Edit Product Image]"?: PrimitiveOverrideProps<TextProps>;
    "Button Child Frame6313"?: PrimitiveOverrideProps<ViewProps>;
    "Button 16314"?: PrimitiveOverrideProps<ViewProps>;
    "Text 16315"?: PrimitiveOverrideProps<TextProps>;
    "[Edit]1486"?: PrimitiveOverrideProps<TextProps>;
    "[Edit]1487"?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 9"?: PrimitiveOverrideProps<IconProps>;
    save?: PrimitiveOverrideProps<TextProps>;
    "Business Page Analytics "?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4643420"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 47"?: PrimitiveOverrideProps<ViewProps>;
    "Header Logo43421"?: PrimitiveOverrideProps<ImageProps>;
    "Header background 43422"?: PrimitiveOverrideProps<ViewProps>;
    "Profile [default pic]43423"?: PrimitiveOverrideProps<IconProps>;
    Dashboard43424?: PrimitiveOverrideProps<TextProps>;
    Analytics43425?: PrimitiveOverrideProps<TextProps>;
    "Product Catalog43426"?: PrimitiveOverrideProps<TextProps>;
    "[ biz name] Dashboard43427"?: PrimitiveOverrideProps<TextProps>;
    Analytics43428?: PrimitiveOverrideProps<TextProps>;
    "Most Popular Products"?: PrimitiveOverrideProps<TextProps>;
    "Business Page Views"?: PrimitiveOverrideProps<TextProps>;
    Item43474?: PrimitiveOverrideProps<ViewProps>;
    "Product background43475"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo43476"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name43477"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range43478"?: PrimitiveOverrideProps<TextProps>;
    Ratings43479?: PrimitiveOverrideProps<ViewProps>;
    Star43480?: PrimitiveOverrideProps<IconProps>;
    Star43481?: PrimitiveOverrideProps<IconProps>;
    Star43482?: PrimitiveOverrideProps<IconProps>;
    Star43483?: PrimitiveOverrideProps<IconProps>;
    Star43484?: PrimitiveOverrideProps<IconProps>;
    Item43518?: PrimitiveOverrideProps<ViewProps>;
    "Product background43519"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo43520"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name43521"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range43522"?: PrimitiveOverrideProps<TextProps>;
    Ratings43523?: PrimitiveOverrideProps<ViewProps>;
    Star43524?: PrimitiveOverrideProps<IconProps>;
    Star43525?: PrimitiveOverrideProps<IconProps>;
    Star43526?: PrimitiveOverrideProps<IconProps>;
    Star43527?: PrimitiveOverrideProps<IconProps>;
    Star43528?: PrimitiveOverrideProps<IconProps>;
    Item43562?: PrimitiveOverrideProps<ViewProps>;
    "Product background43563"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo43564"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name43565"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range43566"?: PrimitiveOverrideProps<TextProps>;
    Ratings43567?: PrimitiveOverrideProps<ViewProps>;
    Star43568?: PrimitiveOverrideProps<IconProps>;
    Star43569?: PrimitiveOverrideProps<IconProps>;
    Star43570?: PrimitiveOverrideProps<IconProps>;
    Star43571?: PrimitiveOverrideProps<IconProps>;
    Star43572?: PrimitiveOverrideProps<IconProps>;
    "Button Child Frame43773"?: PrimitiveOverrideProps<ViewProps>;
    "Button 143774"?: PrimitiveOverrideProps<ViewProps>;
    "Text 143775"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 49"?: PrimitiveOverrideProps<ViewProps>;
    "Button Child Frame43806"?: PrimitiveOverrideProps<ViewProps>;
    "Button 143807"?: PrimitiveOverrideProps<ViewProps>;
    "Text 143808"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 48"?: PrimitiveOverrideProps<ViewProps>;
    "Button Child Frame43801"?: PrimitiveOverrideProps<ViewProps>;
    "Button 143802"?: PrimitiveOverrideProps<ViewProps>;
    "Text 143803"?: PrimitiveOverrideProps<TextProps>;
    "Line chart"?: PrimitiveOverrideProps<ViewProps>;
    Rectangle?: PrimitiveOverrideProps<ViewProps>;
    "X-axis grid43722"?: PrimitiveOverrideProps<IconProps>;
    "X-axis grid43724"?: PrimitiveOverrideProps<IconProps>;
    "X-axis grid43726"?: PrimitiveOverrideProps<IconProps>;
    "X-axis grid43728"?: PrimitiveOverrideProps<IconProps>;
    "X-axis grid43730"?: PrimitiveOverrideProps<IconProps>;
    "Y-axis grid43732"?: PrimitiveOverrideProps<IconProps>;
    "Y-axis grid43734"?: PrimitiveOverrideProps<IconProps>;
    "Y-axis grid43736"?: PrimitiveOverrideProps<IconProps>;
    "Y-axis grid43738"?: PrimitiveOverrideProps<IconProps>;
    "Y-axis grid43740"?: PrimitiveOverrideProps<IconProps>;
    "X-axis"?: PrimitiveOverrideProps<IconProps>;
    "Y-axis"?: PrimitiveOverrideProps<IconProps>;
    AUG?: PrimitiveOverrideProps<TextProps>;
    SEP?: PrimitiveOverrideProps<TextProps>;
    OCT?: PrimitiveOverrideProps<TextProps>;
    NOV?: PrimitiveOverrideProps<TextProps>;
    DEC?: PrimitiveOverrideProps<TextProps>;
    Marker43756?: PrimitiveOverrideProps<IconProps>;
    "Frame 4"?: PrimitiveOverrideProps<FlexProps>;
    "Active Users"?: PrimitiveOverrideProps<TextProps>;
    Line?: PrimitiveOverrideProps<IconProps>;
    Marker43761?: PrimitiveOverrideProps<IconProps>;
    Marker43763?: PrimitiveOverrideProps<IconProps>;
    Marker43765?: PrimitiveOverrideProps<IconProps>;
    Marker43767?: PrimitiveOverrideProps<IconProps>;
    Marker43769?: PrimitiveOverrideProps<IconProps>;
    "# Of Purchases43809"?: PrimitiveOverrideProps<TextProps>;
    "# Of Purchases43811"?: PrimitiveOverrideProps<TextProps>;
    "# Of Purchases43810"?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type User2BusinessProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: User2BusinessOverridesProps | undefined | null;
}>;
export default function User2Business(props: User2BusinessProps): React.ReactElement;
