/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
import { Component1Props } from "./Component1";
import { Group1Props } from "./Group1";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type User1UnlocalLocalCustomerOverridesProps = {
    User1UnlocalLocalCustomer?: PrimitiveOverrideProps<ViewProps>;
    "Homepage not logged in"?: PrimitiveOverrideProps<ViewProps>;
    "search bar1947"?: PrimitiveOverrideProps<ViewProps>;
    "search-icon1948"?: PrimitiveOverrideProps<ImageProps>;
    "search-bar-div1949"?: PrimitiveOverrideProps<IconProps>;
    Filter1950?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 9585"?: PrimitiveOverrideProps<IconProps>;
    Item4632?: PrimitiveOverrideProps<ViewProps>;
    "Product background4633"?: PrimitiveOverrideProps<IconProps>;
    "Product background4645"?: PrimitiveOverrideProps<IconProps>;
    Featured2067?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 442071"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 432070"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 452072"?: PrimitiveOverrideProps<ViewProps>;
    "Business #22073"?: PrimitiveOverrideProps<TextProps>;
    "Business #32074"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 412068"?: PrimitiveOverrideProps<ViewProps>;
    Item5812?: PrimitiveOverrideProps<ViewProps>;
    "Product background5813"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 475816"?: PrimitiveOverrideProps<IconProps>;
    "Business #15818"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 5015916"?: PrimitiveOverrideProps<ViewProps>;
    "Component 1"?: Component1Props;
    "Local finds183"?: PrimitiveOverrideProps<TextProps>;
    "Group 1"?: Group1Props;
    Categories184?: PrimitiveOverrideProps<TextProps>;
    Search1977?: PrimitiveOverrideProps<TextProps>;
    "Top Sellers185"?: PrimitiveOverrideProps<TextProps>;
    "User can create an account"?: PrimitiveOverrideProps<ViewProps>;
    "3FD6D1E0-911A-432E-BBDE-051FB4C400F3 1188"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 52622"?: PrimitiveOverrideProps<ViewProps>;
    Header1810?: PrimitiveOverrideProps<ViewProps>;
    "Top Sellers1811"?: PrimitiveOverrideProps<TextProps>;
    Categories1812?: PrimitiveOverrideProps<TextProps>;
    Icon1813?: PrimitiveOverrideProps<TextProps>;
    "Local Finds1815"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 381952"?: PrimitiveOverrideProps<ViewProps>;
    "Username*"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 391957"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 40"?: PrimitiveOverrideProps<ViewProps>;
    "Email*"?: PrimitiveOverrideProps<TextProps>;
    "Password*"?: PrimitiveOverrideProps<TextProps>;
    "Static Button Customer768"?: PrimitiveOverrideProps<ViewProps>;
    "I am a customer"?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 10766"?: PrimitiveOverrideProps<IconProps>;
    "Static Button Customer769"?: PrimitiveOverrideProps<ViewProps>;
    "I am a business or business owner"?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 107611"?: PrimitiveOverrideProps<IconProps>;
    "Already have an account?"?: PrimitiveOverrideProps<TextProps>;
    "Register Button"?: PrimitiveOverrideProps<ViewProps>;
    "Group 21964"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 371965"?: PrimitiveOverrideProps<ViewProps>;
    Register?: PrimitiveOverrideProps<TextProps>;
    "User can post reviews about a business"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 311882"?: PrimitiveOverrideProps<ViewProps>;
    "3FD6D1E0-911A-432E-BBDE-051FB4C400F3 2"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 8"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 7"?: PrimitiveOverrideProps<ViewProps>;
    "Top Sellers1886"?: PrimitiveOverrideProps<TextProps>;
    "Top Sellers1887"?: PrimitiveOverrideProps<TextProps>;
    Categories1888?: PrimitiveOverrideProps<TextProps>;
    Search1889?: PrimitiveOverrideProps<TextProps>;
    "Local Finds1890"?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 1"?: PrimitiveOverrideProps<IconProps>;
    "Profile Banner"?: PrimitiveOverrideProps<IconProps>;
    "Edit Button"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 32"?: PrimitiveOverrideProps<ViewProps>;
    "map 1"?: PrimitiveOverrideProps<ImageProps>;
    Distance?: PrimitiveOverrideProps<TextProps>;
    Category?: PrimitiveOverrideProps<TextProps>;
    Rating?: PrimitiveOverrideProps<TextProps>;
    "Business Name"?: PrimitiveOverrideProps<TextProps>;
    "Banner Image"?: PrimitiveOverrideProps<TextProps>;
    "page-div"?: PrimitiveOverrideProps<IconProps>;
    "Scrollbar Frame18102"?: PrimitiveOverrideProps<ViewProps>;
    Scrollbar18103?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 33"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 34"?: PrimitiveOverrideProps<ViewProps>;
    "Screenshot 2022-11-21 at 7.10 1"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 35"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 36"?: PrimitiveOverrideProps<ViewProps>;
    "Business Profile 3"?: PrimitiveOverrideProps<ViewProps>;
    "bid-profile118111"?: PrimitiveOverrideProps<ViewProps>;
    "<----------------------- Review Goes Here ----------------------->18112"?: PrimitiveOverrideProps<TextProps>;
    "Review Title18113"?: PrimitiveOverrideProps<TextProps>;
    "@username18114"?: PrimitiveOverrideProps<TextProps>;
    "User Name18115"?: PrimitiveOverrideProps<TextProps>;
    "user-icon18116"?: PrimitiveOverrideProps<IconProps>;
    "Business Profile 4"?: PrimitiveOverrideProps<ViewProps>;
    "bid-profile118118"?: PrimitiveOverrideProps<ViewProps>;
    "<----------------------- Review Goes Here ----------------------->18119"?: PrimitiveOverrideProps<TextProps>;
    "Review Title18120"?: PrimitiveOverrideProps<TextProps>;
    "@username18121"?: PrimitiveOverrideProps<TextProps>;
    "User Name18122"?: PrimitiveOverrideProps<TextProps>;
    "user-icon18123"?: PrimitiveOverrideProps<IconProps>;
    "User can sign into their account"?: PrimitiveOverrideProps<ViewProps>;
    "3FD6D1E0-911A-432E-BBDE-051FB4C400F3 17741"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 527742"?: PrimitiveOverrideProps<ViewProps>;
    Header7744?: PrimitiveOverrideProps<ViewProps>;
    "Top Sellers7745"?: PrimitiveOverrideProps<TextProps>;
    Categories7746?: PrimitiveOverrideProps<TextProps>;
    Icon7747?: PrimitiveOverrideProps<TextProps>;
    "Local Finds7748"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 387749"?: PrimitiveOverrideProps<ViewProps>;
    "Username/Email"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 397751"?: PrimitiveOverrideProps<ViewProps>;
    Password?: PrimitiveOverrideProps<TextProps>;
    "Need an account?"?: PrimitiveOverrideProps<TextProps>;
    "Log IN Button"?: PrimitiveOverrideProps<ViewProps>;
    "Group 27763"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 377764"?: PrimitiveOverrideProps<ViewProps>;
    "Log In"?: PrimitiveOverrideProps<TextProps>;
    or7873?: PrimitiveOverrideProps<ViewProps>;
    or7870?: PrimitiveOverrideProps<TextProps>;
    "Line 2"?: PrimitiveOverrideProps<IconProps>;
    "Line 3"?: PrimitiveOverrideProps<IconProps>;
    "SSO Icons"?: PrimitiveOverrideProps<ViewProps>;
    "search-2 1"?: PrimitiveOverrideProps<ImageProps>;
    "apple-black-logo 1"?: PrimitiveOverrideProps<ImageProps>;
    "facebook 1"?: PrimitiveOverrideProps<ImageProps>;
    "Authentication Screen"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 31813"?: PrimitiveOverrideProps<ViewProps>;
    "Screenshot 2022-11-30 at 10.26 1"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 54"?: PrimitiveOverrideProps<ViewProps>;
    "Registration confirmation "?: PrimitiveOverrideProps<ViewProps>;
    "3FD6D1E0-911A-432E-BBDE-051FB4C400F3 1463"?: PrimitiveOverrideProps<ImageProps>;
    Header465?: PrimitiveOverrideProps<ViewProps>;
    "Top Sellers466"?: PrimitiveOverrideProps<TextProps>;
    Categories467?: PrimitiveOverrideProps<TextProps>;
    Icon468?: PrimitiveOverrideProps<TextProps>;
    "Local Finds469"?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 97718"?: PrimitiveOverrideProps<IconProps>;
    Item7719?: PrimitiveOverrideProps<ViewProps>;
    "Product background7720"?: PrimitiveOverrideProps<IconProps>;
    "Product background7721"?: PrimitiveOverrideProps<IconProps>;
    Featured7722?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 447723"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 437724"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 457725"?: PrimitiveOverrideProps<ViewProps>;
    "Business #27726"?: PrimitiveOverrideProps<TextProps>;
    "Business #37727"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 417728"?: PrimitiveOverrideProps<ViewProps>;
    Item7729?: PrimitiveOverrideProps<ViewProps>;
    "Product background7730"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 477731"?: PrimitiveOverrideProps<IconProps>;
    "Business #17732"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 49"?: PrimitiveOverrideProps<ViewProps>;
    Scrollbar7737?: PrimitiveOverrideProps<ViewProps>;
    "Scrollbar Frame7734"?: PrimitiveOverrideProps<ViewProps>;
    Scrollbar7735?: PrimitiveOverrideProps<ViewProps>;
    "Search-bar"?: PrimitiveOverrideProps<ViewProps>;
    "search bar7713"?: PrimitiveOverrideProps<ViewProps>;
    "search-icon7714"?: PrimitiveOverrideProps<ImageProps>;
    "search-bar-div7715"?: PrimitiveOverrideProps<IconProps>;
    Filter7716?: PrimitiveOverrideProps<TextProps>;
    "User 7712"?: PrimitiveOverrideProps<IconProps>;
    Banner?: PrimitiveOverrideProps<ViewProps>;
    "Frame 2"?: PrimitiveOverrideProps<FlexProps>;
    "Account Registration Successful!"?: PrimitiveOverrideProps<TextProps>;
    "Loading Screen "?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 311593"?: PrimitiveOverrideProps<ViewProps>;
    "Current Logo"?: PrimitiveOverrideProps<ImageProps>;
    "Scrollbar Frame2076"?: PrimitiveOverrideProps<ViewProps>;
    Scrollbar2077?: PrimitiveOverrideProps<ViewProps>;
    "Homepage logged in"?: PrimitiveOverrideProps<ViewProps>;
    "Header Logo"?: PrimitiveOverrideProps<ImageProps>;
    "search bar2054"?: PrimitiveOverrideProps<ViewProps>;
    "search-icon2055"?: PrimitiveOverrideProps<ImageProps>;
    "search-bar-div2056"?: PrimitiveOverrideProps<IconProps>;
    Filter2057?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 92058"?: PrimitiveOverrideProps<IconProps>;
    Item2059?: PrimitiveOverrideProps<ViewProps>;
    "Product background20510"?: PrimitiveOverrideProps<IconProps>;
    "Product background20511"?: PrimitiveOverrideProps<IconProps>;
    Featured20512?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 4420513"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4320514"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 4520515"?: PrimitiveOverrideProps<ViewProps>;
    "Business #220516"?: PrimitiveOverrideProps<TextProps>;
    "Business #320517"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 4120518"?: PrimitiveOverrideProps<ViewProps>;
    Item20519?: PrimitiveOverrideProps<ViewProps>;
    "Product background20520"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 4720521"?: PrimitiveOverrideProps<IconProps>;
    "Business #120522"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 5020523"?: PrimitiveOverrideProps<ViewProps>;
    "Header background "?: PrimitiveOverrideProps<ViewProps>;
    "User 20534"?: PrimitiveOverrideProps<IconProps>;
    Categories20527?: PrimitiveOverrideProps<TextProps>;
    Search1978?: PrimitiveOverrideProps<TextProps>;
    Categories19716?: PrimitiveOverrideProps<TextProps>;
    "Top Sellers20528"?: PrimitiveOverrideProps<TextProps>;
    "Local finds20525"?: PrimitiveOverrideProps<TextProps>;
    "Scrollbar Frame20529"?: PrimitiveOverrideProps<ViewProps>;
    Scrollbar20530?: PrimitiveOverrideProps<ViewProps>;
} & EscapeHatchProps;
export declare type User1UnlocalLocalCustomerProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: User1UnlocalLocalCustomerOverridesProps | undefined | null;
}>;
export default function User1UnlocalLocalCustomer(props: User1UnlocalLocalCustomerProps): React.ReactElement;
