/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
import { UsercanfindbusinessinareaProps } from "./Usercanfindbusinessinarea";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type User1SocialMediaInfluencerOverridesProps = {
    User1SocialMediaInfluencer?: PrimitiveOverrideProps<ViewProps>;
    "Uer can view search history"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 3136160"?: PrimitiveOverrideProps<ViewProps>;
    "3FD6D1E0-911A-432E-BBDE-051FB4C400F3 2617"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 8618"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 7619"?: PrimitiveOverrideProps<ViewProps>;
    Categories629?: PrimitiveOverrideProps<TextProps>;
    Search?: PrimitiveOverrideProps<TextProps>;
    "Local Finds631"?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 1620"?: PrimitiveOverrideProps<IconProps>;
    "Previous Search38169"?: PrimitiveOverrideProps<TextProps>;
    "search bar38165"?: PrimitiveOverrideProps<ViewProps>;
    "Previous Search38170"?: PrimitiveOverrideProps<TextProps>;
    "search bar38171"?: PrimitiveOverrideProps<ViewProps>;
    "Previous Search38172"?: PrimitiveOverrideProps<TextProps>;
    "search bar38173"?: PrimitiveOverrideProps<ViewProps>;
    "Previous Search38174"?: PrimitiveOverrideProps<TextProps>;
    "search bar38175"?: PrimitiveOverrideProps<ViewProps>;
    "Previous Search38176"?: PrimitiveOverrideProps<TextProps>;
    "search bar38177"?: PrimitiveOverrideProps<ViewProps>;
    "Previous Search38178"?: PrimitiveOverrideProps<TextProps>;
    "search bar38179"?: PrimitiveOverrideProps<ViewProps>;
    "search bar38161"?: PrimitiveOverrideProps<ViewProps>;
    "search-icon38162"?: PrimitiveOverrideProps<ImageProps>;
    "search-bar-div38163"?: PrimitiveOverrideProps<IconProps>;
    Filter38164?: PrimitiveOverrideProps<TextProps>;
    "Top Sellers2024"?: PrimitiveOverrideProps<TextProps>;
    "User can search for a new business "?: PrimitiveOverrideProps<ViewProps>;
    "User can find business in area"?: UsercanfindbusinessinareaProps;
    "User can find item in area"?: PrimitiveOverrideProps<ViewProps>;
    "3FD6D1E0-911A-432E-BBDE-051FB4C400F3 1"?: PrimitiveOverrideProps<ImageProps>;
    Header?: PrimitiveOverrideProps<ViewProps>;
    "Top Sellers256"?: PrimitiveOverrideProps<TextProps>;
    Categories257?: PrimitiveOverrideProps<TextProps>;
    Icon?: PrimitiveOverrideProps<TextProps>;
    "User "?: PrimitiveOverrideProps<IconProps>;
    "Local Finds2510"?: PrimitiveOverrideProps<TextProps>;
    "expand profile"?: PrimitiveOverrideProps<IconProps>;
    "search bar2512"?: PrimitiveOverrideProps<ViewProps>;
    "search-icon2513"?: PrimitiveOverrideProps<ImageProps>;
    "search-bar-div2514"?: PrimitiveOverrideProps<IconProps>;
    Filter2515?: PrimitiveOverrideProps<TextProps>;
    "page-div2516"?: PrimitiveOverrideProps<IconProps>;
    "Left Side Bar2564"?: PrimitiveOverrideProps<ViewProps>;
    "Side bar2563"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 2"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 5"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 3"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 4"?: PrimitiveOverrideProps<IconProps>;
    "filter results"?: PrimitiveOverrideProps<TextProps>;
    "Open Now"?: PrimitiveOverrideProps<TextProps>;
    "Price Range"?: PrimitiveOverrideProps<TextProps>;
    Ratings2572?: PrimitiveOverrideProps<TextProps>;
    "within 50 mi"?: PrimitiveOverrideProps<TextProps>;
    "Scrollbar Frame2574"?: PrimitiveOverrideProps<ViewProps>;
    Scrollbar2575?: PrimitiveOverrideProps<ViewProps>;
    Item2586?: PrimitiveOverrideProps<ViewProps>;
    "Product background2576"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo2577"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name2578"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range2579"?: PrimitiveOverrideProps<TextProps>;
    Ratings2585?: PrimitiveOverrideProps<ViewProps>;
    Star2580?: PrimitiveOverrideProps<IconProps>;
    Star2581?: PrimitiveOverrideProps<IconProps>;
    Star2582?: PrimitiveOverrideProps<IconProps>;
    Star2583?: PrimitiveOverrideProps<IconProps>;
    Star2584?: PrimitiveOverrideProps<IconProps>;
    Item2598?: PrimitiveOverrideProps<ViewProps>;
    "Product background2599"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo25100"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name25101"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range25102"?: PrimitiveOverrideProps<TextProps>;
    Ratings25103?: PrimitiveOverrideProps<ViewProps>;
    Star25104?: PrimitiveOverrideProps<IconProps>;
    Star25105?: PrimitiveOverrideProps<IconProps>;
    Star25106?: PrimitiveOverrideProps<IconProps>;
    Star25107?: PrimitiveOverrideProps<IconProps>;
    Star25108?: PrimitiveOverrideProps<IconProps>;
    Item2587?: PrimitiveOverrideProps<ViewProps>;
    "Product background2588"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo2589"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name2590"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range2591"?: PrimitiveOverrideProps<TextProps>;
    Ratings2592?: PrimitiveOverrideProps<ViewProps>;
    Star2593?: PrimitiveOverrideProps<IconProps>;
    Star2594?: PrimitiveOverrideProps<IconProps>;
    Star2595?: PrimitiveOverrideProps<IconProps>;
    Star2596?: PrimitiveOverrideProps<IconProps>;
    Star2597?: PrimitiveOverrideProps<IconProps>;
    Item25175?: PrimitiveOverrideProps<ViewProps>;
    "Product background25176"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo25177"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name25178"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range25179"?: PrimitiveOverrideProps<TextProps>;
    Ratings25180?: PrimitiveOverrideProps<ViewProps>;
    Star25181?: PrimitiveOverrideProps<IconProps>;
    Star25182?: PrimitiveOverrideProps<IconProps>;
    Star25183?: PrimitiveOverrideProps<IconProps>;
    Star25184?: PrimitiveOverrideProps<IconProps>;
    Star25185?: PrimitiveOverrideProps<IconProps>;
    Item25186?: PrimitiveOverrideProps<ViewProps>;
    "Product background25187"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo25188"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name25189"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range25190"?: PrimitiveOverrideProps<TextProps>;
    Ratings25191?: PrimitiveOverrideProps<ViewProps>;
    Star25192?: PrimitiveOverrideProps<IconProps>;
    Star25193?: PrimitiveOverrideProps<IconProps>;
    Star25194?: PrimitiveOverrideProps<IconProps>;
    Star25195?: PrimitiveOverrideProps<IconProps>;
    Star25196?: PrimitiveOverrideProps<IconProps>;
    Item25197?: PrimitiveOverrideProps<ViewProps>;
    "Product background25198"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo25199"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name25200"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range25201"?: PrimitiveOverrideProps<TextProps>;
    Ratings25202?: PrimitiveOverrideProps<ViewProps>;
    Star25203?: PrimitiveOverrideProps<IconProps>;
    Star25204?: PrimitiveOverrideProps<IconProps>;
    Star25205?: PrimitiveOverrideProps<IconProps>;
    Star25206?: PrimitiveOverrideProps<IconProps>;
    Star25207?: PrimitiveOverrideProps<IconProps>;
    Item25142?: PrimitiveOverrideProps<ViewProps>;
    "Product background25143"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo25144"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name25145"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range25146"?: PrimitiveOverrideProps<TextProps>;
    Ratings25147?: PrimitiveOverrideProps<ViewProps>;
    Star25148?: PrimitiveOverrideProps<IconProps>;
    Star25149?: PrimitiveOverrideProps<IconProps>;
    Star25150?: PrimitiveOverrideProps<IconProps>;
    Star25151?: PrimitiveOverrideProps<IconProps>;
    Star25152?: PrimitiveOverrideProps<IconProps>;
    Item25153?: PrimitiveOverrideProps<ViewProps>;
    "Product background25154"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo25155"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name25156"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range25157"?: PrimitiveOverrideProps<TextProps>;
    Ratings25158?: PrimitiveOverrideProps<ViewProps>;
    Star25159?: PrimitiveOverrideProps<IconProps>;
    Star25160?: PrimitiveOverrideProps<IconProps>;
    Star25161?: PrimitiveOverrideProps<IconProps>;
    Star25162?: PrimitiveOverrideProps<IconProps>;
    Star25163?: PrimitiveOverrideProps<IconProps>;
    Item25164?: PrimitiveOverrideProps<ViewProps>;
    "Product background25165"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo25166"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name25167"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range25168"?: PrimitiveOverrideProps<TextProps>;
    Ratings25169?: PrimitiveOverrideProps<ViewProps>;
    Star25170?: PrimitiveOverrideProps<IconProps>;
    Star25171?: PrimitiveOverrideProps<IconProps>;
    Star25172?: PrimitiveOverrideProps<IconProps>;
    Star25173?: PrimitiveOverrideProps<IconProps>;
    Star25174?: PrimitiveOverrideProps<IconProps>;
    Item25109?: PrimitiveOverrideProps<ViewProps>;
    "Product background25110"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo25111"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name25112"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range25113"?: PrimitiveOverrideProps<TextProps>;
    Ratings25114?: PrimitiveOverrideProps<ViewProps>;
    Star25115?: PrimitiveOverrideProps<IconProps>;
    Star25116?: PrimitiveOverrideProps<IconProps>;
    Star25117?: PrimitiveOverrideProps<IconProps>;
    Star25118?: PrimitiveOverrideProps<IconProps>;
    Star25119?: PrimitiveOverrideProps<IconProps>;
    Item25120?: PrimitiveOverrideProps<ViewProps>;
    "Product background25121"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo25122"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name25123"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range25124"?: PrimitiveOverrideProps<TextProps>;
    Ratings25125?: PrimitiveOverrideProps<ViewProps>;
    Star25126?: PrimitiveOverrideProps<IconProps>;
    Star25127?: PrimitiveOverrideProps<IconProps>;
    Star25128?: PrimitiveOverrideProps<IconProps>;
    Star25129?: PrimitiveOverrideProps<IconProps>;
    Star25130?: PrimitiveOverrideProps<IconProps>;
    Item25131?: PrimitiveOverrideProps<ViewProps>;
    "Product background25132"?: PrimitiveOverrideProps<ViewProps>;
    "Item Photo25133"?: PrimitiveOverrideProps<ViewProps>;
    "Product Name25134"?: PrimitiveOverrideProps<TextProps>;
    "Avg Price Range25135"?: PrimitiveOverrideProps<TextProps>;
    Ratings25136?: PrimitiveOverrideProps<ViewProps>;
    Star25137?: PrimitiveOverrideProps<IconProps>;
    Star25138?: PrimitiveOverrideProps<IconProps>;
    Star25139?: PrimitiveOverrideProps<IconProps>;
    Star25140?: PrimitiveOverrideProps<IconProps>;
    Star25141?: PrimitiveOverrideProps<IconProps>;
    "User can post reviews about a business"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 316307"?: PrimitiveOverrideProps<ViewProps>;
    "3FD6D1E0-911A-432E-BBDE-051FB4C400F3 2632"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 8633"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 7634"?: PrimitiveOverrideProps<ViewProps>;
    "Top Sellers635"?: PrimitiveOverrideProps<TextProps>;
    "Top Sellers6305"?: PrimitiveOverrideProps<TextProps>;
    Categories636?: PrimitiveOverrideProps<TextProps>;
    search637?: PrimitiveOverrideProps<TextProps>;
    "Local Finds638"?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 1639"?: PrimitiveOverrideProps<IconProps>;
    "Profile Banner"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 32"?: PrimitiveOverrideProps<ViewProps>;
    Distance?: PrimitiveOverrideProps<TextProps>;
    Category?: PrimitiveOverrideProps<TextProps>;
    Rating?: PrimitiveOverrideProps<TextProps>;
    "Business Name144"?: PrimitiveOverrideProps<TextProps>;
    "Banner Image"?: PrimitiveOverrideProps<TextProps>;
    "page-div1411"?: PrimitiveOverrideProps<IconProps>;
    "Scrollbar Frame1412"?: PrimitiveOverrideProps<ViewProps>;
    Scrollbar1413?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 331532"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 341533"?: PrimitiveOverrideProps<ViewProps>;
    "Screenshot 2022-11-21 at 7.10 1"?: PrimitiveOverrideProps<ImageProps>;
    Star2922?: PrimitiveOverrideProps<IconProps>;
    Star2923?: PrimitiveOverrideProps<IconProps>;
    Star2924?: PrimitiveOverrideProps<IconProps>;
    Star2925?: PrimitiveOverrideProps<IconProps>;
    Star2926?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 35"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 36"?: PrimitiveOverrideProps<ViewProps>;
    "Business Profile 11523"?: PrimitiveOverrideProps<ViewProps>;
    "bid-profile11524"?: PrimitiveOverrideProps<ViewProps>;
    "<----------------------- Review Goes Here ----------------------->1528"?: PrimitiveOverrideProps<TextProps>;
    "Review Title1535"?: PrimitiveOverrideProps<TextProps>;
    "@username1527"?: PrimitiveOverrideProps<TextProps>;
    "User Name1525"?: PrimitiveOverrideProps<TextProps>;
    "user-icon1536"?: PrimitiveOverrideProps<IconProps>;
    Star2927?: PrimitiveOverrideProps<IconProps>;
    Star2928?: PrimitiveOverrideProps<IconProps>;
    Star2929?: PrimitiveOverrideProps<IconProps>;
    Star2930?: PrimitiveOverrideProps<IconProps>;
    Star2931?: PrimitiveOverrideProps<IconProps>;
    "Business Profile 21538"?: PrimitiveOverrideProps<ViewProps>;
    "bid-profile11539"?: PrimitiveOverrideProps<ViewProps>;
    "<----------------------- Review Goes Here ----------------------->1540"?: PrimitiveOverrideProps<TextProps>;
    "Review Title1541"?: PrimitiveOverrideProps<TextProps>;
    "@username1542"?: PrimitiveOverrideProps<TextProps>;
    "User Name1543"?: PrimitiveOverrideProps<TextProps>;
    "user-icon1544"?: PrimitiveOverrideProps<IconProps>;
    Star292?: PrimitiveOverrideProps<IconProps>;
    Star293?: PrimitiveOverrideProps<IconProps>;
    Star294?: PrimitiveOverrideProps<IconProps>;
    Star295?: PrimitiveOverrideProps<IconProps>;
    Star296?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 513132"?: PrimitiveOverrideProps<ViewProps>;
    Post?: PrimitiveOverrideProps<TextProps>;
    "Post Review"?: PrimitiveOverrideProps<TextProps>;
    "User can edit their profile 1"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 3138181"?: PrimitiveOverrideProps<ViewProps>;
    "Side bar40201"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 5141226"?: PrimitiveOverrideProps<ViewProps>;
    "Edit Profile"?: PrimitiveOverrideProps<TextProps>;
    "Left Side Bar40202"?: PrimitiveOverrideProps<ViewProps>;
    Location?: PrimitiveOverrideProps<TextProps>;
    "image 140220"?: PrimitiveOverrideProps<ImageProps>;
    "@username40211"?: PrimitiveOverrideProps<TextProps>;
    "User Name40208"?: PrimitiveOverrideProps<TextProps>;
    "Profile picture40200"?: PrimitiveOverrideProps<IconProps>;
    "3FD6D1E0-911A-432E-BBDE-051FB4C400F3 238182"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 838183"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 738184"?: PrimitiveOverrideProps<ViewProps>;
    "Top Sellers38185"?: PrimitiveOverrideProps<TextProps>;
    "Top Sellers38186"?: PrimitiveOverrideProps<TextProps>;
    Categories38187?: PrimitiveOverrideProps<TextProps>;
    search38188?: PrimitiveOverrideProps<TextProps>;
    "Local Finds38189"?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 138190"?: PrimitiveOverrideProps<IconProps>;
    "Edit Button39199"?: PrimitiveOverrideProps<ImageProps>;
    "Group 3"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 3441257"?: PrimitiveOverrideProps<ViewProps>;
    "Business Profile 4"?: PrimitiveOverrideProps<ViewProps>;
    "bid-profile141229"?: PrimitiveOverrideProps<ViewProps>;
    "Business Name41230"?: PrimitiveOverrideProps<TextProps>;
    "Category | Rating41231"?: PrimitiveOverrideProps<TextProps>;
    "@businessusername41232"?: PrimitiveOverrideProps<TextProps>;
    "business-icon141236"?: PrimitiveOverrideProps<ViewProps>;
    "Business Profile 3"?: PrimitiveOverrideProps<ViewProps>;
    "bid-profile141239"?: PrimitiveOverrideProps<ViewProps>;
    "Business Name41240"?: PrimitiveOverrideProps<TextProps>;
    "Category | Rating41241"?: PrimitiveOverrideProps<TextProps>;
    "@businessusername41242"?: PrimitiveOverrideProps<TextProps>;
    "business-icon141243"?: PrimitiveOverrideProps<ViewProps>;
    "Business Profile 241244"?: PrimitiveOverrideProps<ViewProps>;
    "bid-profile141245"?: PrimitiveOverrideProps<ViewProps>;
    "Business Name41246"?: PrimitiveOverrideProps<TextProps>;
    "Category | Rating41247"?: PrimitiveOverrideProps<TextProps>;
    "@businessusername41248"?: PrimitiveOverrideProps<TextProps>;
    "business-icon141249"?: PrimitiveOverrideProps<ViewProps>;
    "Business Profile 141250"?: PrimitiveOverrideProps<ViewProps>;
    "bid-profile141251"?: PrimitiveOverrideProps<ViewProps>;
    "Business Name41252"?: PrimitiveOverrideProps<TextProps>;
    "Category | Rating41253"?: PrimitiveOverrideProps<TextProps>;
    "@businessusername41254"?: PrimitiveOverrideProps<TextProps>;
    "business-icon141255"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 3341221"?: PrimitiveOverrideProps<ViewProps>;
    Favorites?: PrimitiveOverrideProps<TextProps>;
    "My Reviews41258"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 3441260"?: PrimitiveOverrideProps<ViewProps>;
    "My Review 4"?: PrimitiveOverrideProps<ViewProps>;
    "bid-profile141261"?: PrimitiveOverrideProps<ViewProps>;
    "bid-profile141295"?: PrimitiveOverrideProps<ViewProps>;
    Star41287?: PrimitiveOverrideProps<IconProps>;
    Star41288?: PrimitiveOverrideProps<IconProps>;
    Star41289?: PrimitiveOverrideProps<IconProps>;
    Star41290?: PrimitiveOverrideProps<IconProps>;
    Star41291?: PrimitiveOverrideProps<IconProps>;
    "Business Name41262"?: PrimitiveOverrideProps<TextProps>;
    "@businessusername41264"?: PrimitiveOverrideProps<TextProps>;
    "<----- Review Goes Here ----->41292"?: PrimitiveOverrideProps<TextProps>;
    "My Review 3"?: PrimitiveOverrideProps<ViewProps>;
    "bid-profile141332"?: PrimitiveOverrideProps<ViewProps>;
    "bid-profile141333"?: PrimitiveOverrideProps<ViewProps>;
    Star41334?: PrimitiveOverrideProps<IconProps>;
    Star41335?: PrimitiveOverrideProps<IconProps>;
    Star41336?: PrimitiveOverrideProps<IconProps>;
    Star41337?: PrimitiveOverrideProps<IconProps>;
    Star41338?: PrimitiveOverrideProps<IconProps>;
    "Business Name41339"?: PrimitiveOverrideProps<TextProps>;
    "@businessusername41340"?: PrimitiveOverrideProps<TextProps>;
    "<----- Review Goes Here ----->41341"?: PrimitiveOverrideProps<TextProps>;
    "My Review 2"?: PrimitiveOverrideProps<ViewProps>;
    "bid-profile141321"?: PrimitiveOverrideProps<ViewProps>;
    "bid-profile141322"?: PrimitiveOverrideProps<ViewProps>;
    Star41323?: PrimitiveOverrideProps<IconProps>;
    Star41324?: PrimitiveOverrideProps<IconProps>;
    Star41325?: PrimitiveOverrideProps<IconProps>;
    Star41326?: PrimitiveOverrideProps<IconProps>;
    Star41327?: PrimitiveOverrideProps<IconProps>;
    "Business Name41328"?: PrimitiveOverrideProps<TextProps>;
    "@businessusername41329"?: PrimitiveOverrideProps<TextProps>;
    "<----- Review Goes Here ----->41330"?: PrimitiveOverrideProps<TextProps>;
    "My Review 1"?: PrimitiveOverrideProps<ViewProps>;
    "bid-profile141343"?: PrimitiveOverrideProps<ViewProps>;
    "bid-profile141344"?: PrimitiveOverrideProps<ViewProps>;
    Star41345?: PrimitiveOverrideProps<IconProps>;
    Star41346?: PrimitiveOverrideProps<IconProps>;
    Star41347?: PrimitiveOverrideProps<IconProps>;
    Star41348?: PrimitiveOverrideProps<IconProps>;
    Star41349?: PrimitiveOverrideProps<IconProps>;
    "Business Name41350"?: PrimitiveOverrideProps<TextProps>;
    "@businessusername41351"?: PrimitiveOverrideProps<TextProps>;
    "<----- Review Goes Here ----->41352"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 3341284"?: PrimitiveOverrideProps<ViewProps>;
    "My Reviews41285"?: PrimitiveOverrideProps<TextProps>;
    "User can edit their profile 2"?: PrimitiveOverrideProps<ViewProps>;
    "User can edit their profile"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 31535"?: PrimitiveOverrideProps<ViewProps>;
    "Profile picture5313"?: PrimitiveOverrideProps<IconProps>;
    "Profile picture53113"?: PrimitiveOverrideProps<IconProps>;
    "Edit Profile Picture"?: PrimitiveOverrideProps<TextProps>;
    "Edit Button5323"?: PrimitiveOverrideProps<ImageProps>;
    "3FD6D1E0-911A-432E-BBDE-051FB4C400F3 25314"?: PrimitiveOverrideProps<ImageProps>;
    "Rectangle 85315"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 75316"?: PrimitiveOverrideProps<ViewProps>;
    "Top Sellers5317"?: PrimitiveOverrideProps<TextProps>;
    "Top Sellers5318"?: PrimitiveOverrideProps<TextProps>;
    Categories5319?: PrimitiveOverrideProps<TextProps>;
    search5320?: PrimitiveOverrideProps<TextProps>;
    "Local Finds5321"?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 15322"?: PrimitiveOverrideProps<IconProps>;
    "Edit field"?: PrimitiveOverrideProps<ViewProps>;
    "Side bar53102"?: PrimitiveOverrideProps<IconProps>;
    "image 153100"?: PrimitiveOverrideProps<ImageProps>;
    "text field 2"?: PrimitiveOverrideProps<ViewProps>;
    "Location:"?: PrimitiveOverrideProps<TextProps>;
    "text field 3"?: PrimitiveOverrideProps<ViewProps>;
    "@username:"?: PrimitiveOverrideProps<TextProps>;
    "text field 1"?: PrimitiveOverrideProps<ViewProps>;
    "User Name:"?: PrimitiveOverrideProps<TextProps>;
    Done15412?: PrimitiveOverrideProps<ViewProps>;
    Done15413?: PrimitiveOverrideProps<TextProps>;
    "Arrow 1"?: PrimitiveOverrideProps<IconProps>;
} & EscapeHatchProps;
export declare type User1SocialMediaInfluencerProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: User1SocialMediaInfluencerOverridesProps | undefined | null;
}>;
export default function User1SocialMediaInfluencer(props: User1SocialMediaInfluencerProps): React.ReactElement;
